package redirect;
// Generated 2016/12/31 ¤U¤È 03:58:57 by Hibernate Tools 4.3.1



/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private String ra;
     private String target;

    public Address() {
    }

    public Address(String ra, String target) {
       this.ra = ra;
       this.target = target;
    }
   
    public String getRa() {
        return this.ra;
    }
    
    public void setRa(String ra) {
        this.ra = ra;
    }
    public String getTarget() {
        return this.target;
    }
    
    public void setTarget(String target) {
        this.target = target;
    }




}


