package Random_test;
// Generated 2016/12/27 ¤U¤È 01:54:31 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Test1 generated by hbm2java
 */
public class Test1  implements java.io.Serializable {


     private Integer id;
     private int amount;
     private BigDecimal price;

    public Test1() {
    }

    public Test1(int amount, BigDecimal price) {
       this.amount = amount;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }




}


